

CREATE view [inf].[vQueryStat] as 
select DB_Name(coalesce(ST.[dbid], PT.[dbid])) as [DB_Name]
	   ,OBJECT_SCHEMA_NAME(coalesce(ST.[objectid], PT.[objectid]), coalesce(ST.[dbid], PT.[dbid])) as [Schema_Name]
	   ,object_name(coalesce(ST.[objectid], PT.[objectid]), coalesce(ST.[dbid], PT.[dbid])) as [Trigger_Name]
	  ,QS.[sql_handle]
      ,QS.[statement_start_offset]
      ,QS.[statement_end_offset]
      ,QS.[plan_generation_num]
      ,QS.[plan_handle]
      ,QS.[creation_time]
      ,QS.[last_execution_time]
      ,QS.[execution_count]
      ,QS.[total_worker_time]
      ,QS.[last_worker_time]
      ,QS.[min_worker_time]
      ,QS.[max_worker_time]
      ,QS.[total_physical_reads]
      ,QS.[last_physical_reads]
      ,QS.[min_physical_reads]
      ,QS.[max_physical_reads]
      ,QS.[total_logical_writes]
      ,QS.[last_logical_writes]
      ,QS.[min_logical_writes]
      ,QS.[max_logical_writes]
      ,QS.[total_logical_reads]
      ,QS.[last_logical_reads]
      ,QS.[min_logical_reads]
      ,QS.[max_logical_reads]
      ,QS.[total_clr_time]
      ,QS.[last_clr_time]
      ,QS.[min_clr_time]
      ,QS.[max_clr_time]
      ,QS.[total_elapsed_time]
      ,QS.[last_elapsed_time]
      ,QS.[min_elapsed_time]
      ,QS.[max_elapsed_time]
      ,QS.[query_hash]
      ,QS.[query_plan_hash]
      ,QS.[total_rows]
      ,QS.[last_rows]
      ,QS.[min_rows]
      ,QS.[max_rows]
      ,QS.[statement_sql_handle]
      ,QS.[statement_context_id]
      ,QS.[total_dop]
      ,QS.[last_dop]
      ,QS.[min_dop]
      ,QS.[max_dop]
      ,QS.[total_grant_kb]
      ,QS.[last_grant_kb]
      ,QS.[min_grant_kb]
      ,QS.[max_grant_kb]
      ,QS.[total_used_grant_kb]
      ,QS.[last_used_grant_kb]
      ,QS.[min_used_grant_kb]
      ,QS.[max_used_grant_kb]
      ,QS.[total_ideal_grant_kb]
      ,QS.[last_ideal_grant_kb]
      ,QS.[min_ideal_grant_kb]
      ,QS.[max_ideal_grant_kb]
      ,QS.[total_reserved_threads]
      ,QS.[last_reserved_threads]
      ,QS.[min_reserved_threads]
      ,QS.[max_reserved_threads]
      ,QS.[total_used_threads]
      ,QS.[last_used_threads]
      ,QS.[min_used_threads]
      ,QS.[max_used_threads]
      ,QS.[total_columnstore_segment_reads]
      ,QS.[last_columnstore_segment_reads]
      ,QS.[min_columnstore_segment_reads]
      ,QS.[max_columnstore_segment_reads]
      ,QS.[total_columnstore_segment_skips]
      ,QS.[last_columnstore_segment_skips]
      ,QS.[min_columnstore_segment_skips]
      ,QS.[max_columnstore_segment_skips]
	  ,coalesce(ST.[dbid], PT.[dbid]) as [dbid]
	  ,SCHEMA_ID(OBJECT_SCHEMA_NAME(coalesce(ST.[objectid], PT.[objectid]), coalesce(ST.[dbid], PT.[dbid]))) as [schema_id]
	  ,coalesce(ST.[objectid], PT.[objectid]) as [objectid]
	  ,ST.[encrypted]
	  ,ST.[text] as [TSQL]
	  ,PT.[query_plan]
FROM sys.dm_exec_query_stats AS QS
     CROSS APPLY sys.dm_exec_sql_text(QS.sql_handle) as ST
	 CROSS APPLY sys.dm_exec_query_plan(QS.[plan_handle]) as PT

GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Статистика по запросам', @level0type = N'SCHEMA', @level0name = N'inf', @level1type = N'VIEW', @level1name = N'vQueryStat';

