


	CREATE view [inf].[vRequestLockDetail] as
/*
	ГЕМ: Сведения о запросах-что блокируют и т д
*/
SELECT r.[session_id]
      ,r.[blocking_session_id]
	  ,(select top(1) text from sys.dm_exec_sql_text(r.[sql_handle])) as [TSQL]
	  ,DB_NAME(r.[database_id]) as DBName
	  ,(select top(1) [query_plan] from sys.dm_exec_query_plan(r.[plan_handle])) as [QueryPlan]
	  ,r.[request_id]
      ,r.[start_time]
      ,r.[status]
      ,r.[command]
      ,r.[sql_handle]
      ,r.[statement_start_offset]
      ,r.[statement_end_offset]
      ,r.[plan_handle]
      ,r.[database_id]
      ,r.[user_id]
      ,r.[connection_id]
      ,r.[wait_type]
      ,r.[wait_time]
      ,r.[last_wait_type]
      ,r.[wait_resource]
      ,r.[open_transaction_count]
      ,r.[open_resultset_count]
      ,r.[transaction_id]
      ,r.[context_info]
      ,r.[percent_complete]
      ,r.[estimated_completion_time]
      ,r.[cpu_time]
      ,r.[total_elapsed_time]
      ,r.[scheduler_id]
      ,r.[task_address]
      ,r.[reads]
      ,r.[writes]
      ,r.[logical_reads]
      ,r.[text_size]
      ,r.[language]
      ,r.[date_format]
      ,r.[date_first]
      ,r.[quoted_identifier]
      ,r.[arithabort]
      ,r.[ansi_null_dflt_on]
      ,r.[ansi_defaults]
      ,r.[ansi_warnings]
      ,r.[ansi_padding]
      ,r.[ansi_nulls]
      ,r.[concat_null_yields_null]
      ,r.[transaction_isolation_level]
      ,r.[lock_timeout]
      ,r.[deadlock_priority]
      ,r.[row_count]
      ,r.[prev_error]
      ,r.[nest_level]
      ,r.[granted_query_memory]
      ,r.[executing_managed_code]
      ,r.[group_id]
      ,r.[query_hash]
      ,r.[query_plan_hash]
	  ,lock.[resource_type]
      ,lock.[resource_subtype]
      ,lock.[resource_database_id]
      ,lock.[resource_description]
      ,lock.[resource_associated_entity_id]
      ,lock.[resource_lock_partition]
      ,lock.[request_mode]
      ,lock.[request_type]
      ,lock.[request_status]
      ,lock.[request_reference_count]
      ,lock.[request_session_id]
      ,lock.[request_exec_context_id]
      ,lock.[request_request_id]
      ,lock.[request_owner_type]
      ,lock.[request_owner_id]
      ,lock.[request_owner_guid]
      ,lock.[lock_owner_address]
FROM sys.dm_exec_requests as r
inner join sys.dm_tran_locks as lock on lock.request_owner_id=r.[transaction_id]


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Сведения о запросах (что блокируют и т д) экземпляра MS SQL Server', @level0type = N'SCHEMA', @level0name = N'inf', @level1type = N'VIEW', @level1name = N'vRequestLockDetail';

