CREATE TABLE [srv].[history_dm_db_index_usage_stats] (
    [database_id]        SMALLINT NOT NULL,
    [object_id]          INT      NOT NULL,
    [index_id]           INT      NOT NULL,
    [user_seeks]         BIGINT   NOT NULL,
    [user_scans]         BIGINT   NOT NULL,
    [user_lookups]       BIGINT   NOT NULL,
    [user_updates]       BIGINT   NOT NULL,
    [last_user_seek]     DATETIME NULL,
    [last_user_scan]     DATETIME NULL,
    [last_user_lookup]   DATETIME NULL,
    [last_user_update]   DATETIME NULL,
    [system_seeks]       BIGINT   NOT NULL,
    [system_scans]       BIGINT   NOT NULL,
    [system_lookups]     BIGINT   NOT NULL,
    [system_updates]     BIGINT   NOT NULL,
    [last_system_seek]   DATETIME NULL,
    [last_system_scan]   DATETIME NULL,
    [last_system_lookup] DATETIME NULL,
    [last_system_update] DATETIME NULL,
    [DateInsert]         DATETIME CONSTRAINT [DF__history_d__DateI__0DCF0841] DEFAULT (getdate()) NOT NULL,
    [Id]                 BIGINT   IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK__history___3214EC073A11781B] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 95)
);

