CREATE TABLE [srv].[KillSessionArchive] (
    [ID]                                  INT              IDENTITY (1, 1) NOT NULL,
    [session_id]                          SMALLINT         NOT NULL,
    [session_login_time]                  DATETIME         NOT NULL,
    [session_host_name]                   NVARCHAR (128)   NULL,
    [session_program_name]                NVARCHAR (128)   NULL,
    [session_host_process_id]             INT              NULL,
    [session_client_version]              INT              NULL,
    [session_client_interface_name]       NVARCHAR (32)    NULL,
    [session_security_id]                 VARBINARY (85)   NOT NULL,
    [session_login_name]                  NVARCHAR (128)   NOT NULL,
    [session_nt_domain]                   NVARCHAR (128)   NULL,
    [session_nt_user_name]                NVARCHAR (128)   NULL,
    [session_status]                      NVARCHAR (30)    NOT NULL,
    [session_cpu_time]                    INT              NOT NULL,
    [session_memory_usage]                INT              NOT NULL,
    [session_total_scheduled_time]        INT              NOT NULL,
    [session_total_elapsed_time]          INT              NOT NULL,
    [session_endpoint_id]                 INT              NOT NULL,
    [session_last_request_start_time]     DATETIME         NOT NULL,
    [session_last_request_end_time]       DATETIME         NULL,
    [session_reads]                       BIGINT           NOT NULL,
    [session_writes]                      BIGINT           NOT NULL,
    [session_logical_reads]               BIGINT           NOT NULL,
    [session_is_user_process]             BIT              NOT NULL,
    [session_text_size]                   INT              NOT NULL,
    [session_language]                    NVARCHAR (128)   NULL,
    [session_date_format]                 NVARCHAR (3)     NULL,
    [session_date_first]                  SMALLINT         NOT NULL,
    [session_quoted_identifier]           BIT              NOT NULL,
    [session_arithabort]                  BIT              NOT NULL,
    [session_ansi_null_dflt_on]           BIT              NOT NULL,
    [session_ansi_defaults]               BIT              NOT NULL,
    [session_ansi_warnings]               BIT              NOT NULL,
    [session_ansi_padding]                BIT              NOT NULL,
    [session_ansi_nulls]                  BIT              NOT NULL,
    [session_concat_null_yields_null]     BIT              NOT NULL,
    [session_transaction_isolation_level] SMALLINT         NOT NULL,
    [session_lock_timeout]                INT              NOT NULL,
    [session_deadlock_priority]           INT              NOT NULL,
    [session_row_count]                   BIGINT           NOT NULL,
    [session_prev_error]                  INT              NOT NULL,
    [session_original_security_id]        VARBINARY (85)   NOT NULL,
    [session_original_login_name]         NVARCHAR (128)   NOT NULL,
    [session_last_successful_logon]       DATETIME         NULL,
    [session_last_unsuccessful_logon]     DATETIME         NULL,
    [session_unsuccessful_logons]         BIGINT           NULL,
    [session_group_id]                    INT              NOT NULL,
    [session_database_id]                 SMALLINT         NOT NULL,
    [session_authenticating_database_id]  INT              NULL,
    [session_open_transaction_count]      INT              NOT NULL,
    [request_id]                          INT              NOT NULL,
    [request_start_time]                  DATETIME         NOT NULL,
    [request_status]                      NVARCHAR (30)    NOT NULL,
    [request_command]                     NVARCHAR (32)    NOT NULL,
    [request_sql_handle]                  VARBINARY (64)   NULL,
    [request_statement_start_offset]      INT              NULL,
    [request_statement_end_offset]        INT              NULL,
    [request_plan_handle]                 VARBINARY (64)   NULL,
    [request_user_id]                     INT              NOT NULL,
    [request_connection_id]               UNIQUEIDENTIFIER NULL,
    [request_blocking_session_id]         SMALLINT         NULL,
    [request_wait_type]                   NVARCHAR (60)    NULL,
    [request_wait_time]                   INT              NOT NULL,
    [request_last_wait_type]              NVARCHAR (60)    NOT NULL,
    [request_wait_resource]               NVARCHAR (256)   NOT NULL,
    [request_open_transaction_count]      INT              NOT NULL,
    [request_open_resultset_count]        INT              NOT NULL,
    [request_transaction_id]              BIGINT           NOT NULL,
    [request_percent_complete]            REAL             NOT NULL,
    [request_estimated_completion_time]   BIGINT           NOT NULL,
    [request_cpu_time]                    INT              NOT NULL,
    [request_total_elapsed_time]          INT              NOT NULL,
    [request_scheduler_id]                INT              NULL,
    [request_task_address]                VARBINARY (8)    NULL,
    [request_reads]                       BIGINT           NOT NULL,
    [request_writes]                      BIGINT           NOT NULL,
    [request_logical_reads]               BIGINT           NOT NULL,
    [request_text_size]                   INT              NOT NULL,
    [request_language]                    NVARCHAR (128)   NULL,
    [request_date_format]                 NVARCHAR (3)     NULL,
    [request_date_first]                  SMALLINT         NOT NULL,
    [request_quoted_identifier]           BIT              NOT NULL,
    [request_arithabort]                  BIT              NOT NULL,
    [request_ansi_null_dflt_on]           BIT              NOT NULL,
    [request_ansi_defaults]               BIT              NOT NULL,
    [request_ansi_warnings]               BIT              NOT NULL,
    [request_ansi_padding]                BIT              NOT NULL,
    [request_ansi_nulls]                  BIT              NOT NULL,
    [request_concat_null_yields_null]     BIT              NOT NULL,
    [request_transaction_isolation_level] SMALLINT         NOT NULL,
    [request_lock_timeout]                INT              NOT NULL,
    [request_deadlock_priority]           INT              NOT NULL,
    [request_row_count]                   BIGINT           NOT NULL,
    [request_prev_error]                  INT              NOT NULL,
    [request_nest_level]                  INT              NOT NULL,
    [request_granted_query_memory]        INT              NOT NULL,
    [request_executing_managed_code]      BIT              NOT NULL,
    [request_group_id]                    INT              NOT NULL,
    [request_query_hash]                  BINARY (8)       NULL,
    [request_query_plan_hash]             BINARY (8)       NULL,
    [request_statement_sql_handle]        VARBINARY (64)   NULL,
    [request_statement_context_id]        BIGINT           NULL,
    [request_dop]                         INT              NULL,
    [request_parallel_worker_count]       INT              NULL,
    [request_external_script_request_id]  UNIQUEIDENTIFIER NULL,
    [ERROR_MESSAGE]                       NVARCHAR (4000)  NULL,
    [DBName]                              NVARCHAR (255)   NULL,
    [TSQL]                                NVARCHAR (MAX)   NULL,
    [QueryPlan]                           XML              NULL,
    [InsertUTCDate]                       DATETIME         CONSTRAINT [DF_KillSessionArchive_InsertUTCDate] DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_KillSessionArchive] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 95)
);

